# Generated by Django 5.2.9 on 2026-03-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
