# Generated by Django 5.2.9 on 2026-03-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_order_payment_method_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
